version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "github-actions"

  - package-ecosystem: "npm"
    directory: "/backend-node"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "backend-node"

  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "web"

  - package-ecosystem: "npm"
    directory: "/mobile/eisenhower-matrix"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "mobile"

  - package-ecosystem: "pip"
    directory: "/backend-ai"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    labels:
      - "dependencies"
      - "backend-ai"
